import type { NextPage } from 'next';
import Head from 'next/head';
import Container from '../src/components/based/Container';
import { DailyChallengeWrapper, DailyInfo } from '../src/components/shared/Wrapper';
import Day1 from '../src/views/payment/Day1';

const Home: NextPage = () => {
	return (
		<Container>
			<Head>
				<title>RWD Practicing</title>
				{/* <meta name="description" content="Generated by create next app" /> */}
				{/* <link rel="icon" href="/favicon.ico" /> */}
			</Head>

			<DailyChallengeWrapper info={day1}>
				<Day1 />
			</DailyChallengeWrapper>
		</Container>
	);
};

const day1 = new DailyInfo(
	'day1',
	'Day1',
	'Using percentages & avoiding heights',
	'A look at why fixed unit sizes are a bad idea when it comes to creating layouts, and the times you might want to use them.'
);

export default Home;
