import type { NextPage } from 'next';
import Head from 'next/head';
import Container from '../src/components/based/Container';
import { DailyChallengeWrapper, ChallengeInfo } from '../src/components/shared/Wrapper';
import Challenge1 from '../src/views/payment/Challenge1';

const Home: NextPage = () => {
	return (
		<Container>
			<Head>
				<title>RWD Practicing</title>
				{/* <meta name="description" content="Generated by create next app" /> */}
				{/* <link rel="icon" href="/favicon.ico" /> */}
			</Head>

			<DailyChallengeWrapper info={challenge1}>
				<Challenge1 />
			</DailyChallengeWrapper>
		</Container>
	);
};

const challenge1 = new ChallengeInfo(
	'challenge1',
	'Challenge 1',
	'Using percentages & avoiding heights',
	'A look at why fixed unit sizes are a bad idea when it comes to creating layouts, and the times you might want to use them.'
);

export default Home;
