import type { NextPage } from 'next';
import Head from 'next/head';
import Container from '../src/components/based/Container';
import { DailyChallengeWrapper, ChallengeInfo } from '../src/components/shared/Wrapper';
import Challenge1 from '../src/views/payment/Challenge1';
import Challenge2 from '../src/views/payment/Challenge2';
import Challenge3 from '../src/views/payment/Challenge3';

const Home: NextPage = () => {
	return (
		<Container>
			<Head>
				<title>RWD Practicing</title>
				{/* <meta name="description" content="Generated by create next app" /> */}
				{/* <link rel="icon" href="/favicon.ico" /> */}
			</Head>

			<DailyChallengeWrapper info={challenge1}>
				<Challenge1 />
			</DailyChallengeWrapper>
			<DailyChallengeWrapper info={challenge2}>
				<Challenge2 />
			</DailyChallengeWrapper>
			<DailyChallengeWrapper info={challenge3}>
				<Challenge3 />
			</DailyChallengeWrapper>
		</Container>
	);
};

const challenge1 = new ChallengeInfo(
	'challenge1',
	'Challenge 1',
	'Using percentages & avoiding heights',
	'A look at why fixed unit sizes are a bad idea when it comes to creating layouts, and the times you might want to use them.'
);
const challenge2 = new ChallengeInfo(
	'challenge2',
	'Challenge 2',
	'Enter max-width',
	''
);
const challenge3 = new ChallengeInfo(
	'challenge3',
	'Challenge 3',
	'Try to clone this example',
	<a href="https://www.figma.com/file/dGPcL6Ym2avOt4736aHb2B/conquer-responsive-layout-week-1-final-challenge?node-id=0%3A1">Figma</a>
);

export default Home;
